# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyliner < Formula
  desc "A beautiful, keyboard-driven terminal TUI for Linear"
  homepage "https://github.com/li-brandon/lazyliner"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.2/lazyliner_0.0.2_darwin_amd64.tar.gz"
      sha256 "0914eb5da7c8b78ede8ffddbb0e198ad67635673d5758c93f6322feebb265ada"

      def install
        bin.install "lazyliner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.2/lazyliner_0.0.2_darwin_arm64.tar.gz"
      sha256 "51be0ec07deb2900edf3a27811fb7fe8ea4beab04586a395bf51ecb70b00dc26"

      def install
        bin.install "lazyliner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.2/lazyliner_0.0.2_linux_amd64.tar.gz"
      sha256 "afcf5cc4f3b8636b6282e0843442ef658509976080c0c57daf5edb183fcf6724"
      def install
        bin.install "lazyliner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.2/lazyliner_0.0.2_linux_arm64.tar.gz"
      sha256 "a4f3ce4f96566aafe8d049e78f7f7d47c85849ed1891ab5acbd92e86cf316ae9"
      def install
        bin.install "lazyliner"
      end
    end
  end

  test do
    system "#{bin}/lazyliner", "--version"
  end
end
