# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyliner < Formula
  desc "A beautiful, keyboard-driven terminal TUI for Linear"
  homepage "https://github.com/li-brandon/lazyliner"
  version "0.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.0/lazyliner_0.0.0_darwin_amd64.tar.gz"
      sha256 "d72872bb58389afbe1c12e1580ff5fd858a3a8f4e57530df3687893d90eb27a5"

      def install
        bin.install "lazyliner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.0/lazyliner_0.0.0_darwin_arm64.tar.gz"
      sha256 "28a071cd192a1d01cd295924f8b66ce98c96d8b310bed244826eb38d2212f648"

      def install
        bin.install "lazyliner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.0/lazyliner_0.0.0_linux_amd64.tar.gz"
      sha256 "2afe38b21bc8bfb06cea1b312b21df3384ac2840562a34fe64e8ea4971c14915"
      def install
        bin.install "lazyliner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.0/lazyliner_0.0.0_linux_arm64.tar.gz"
      sha256 "10b3154c671e907aa26dd140e291b6d8c17e3c7b6fa048c94c06b9943acc6083"
      def install
        bin.install "lazyliner"
      end
    end
  end

  test do
    system "#{bin}/lazyliner", "--version"
  end
end
