# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyliner < Formula
  desc "A beautiful, keyboard-driven terminal TUI for Linear"
  homepage "https://github.com/li-brandon/lazyliner"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.1/lazyliner_0.0.1_darwin_amd64.tar.gz"
      sha256 "d9ffe49529d67753583bd6fef3fab3aa1e25ce4226996e79ba30c09b59471d06"

      def install
        bin.install "lazyliner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.1/lazyliner_0.0.1_darwin_arm64.tar.gz"
      sha256 "2ec1c47bbc31e0e5fd7fd925d614a5d0a0f5fbd42db573eadd70d94afeebc53c"

      def install
        bin.install "lazyliner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.1/lazyliner_0.0.1_linux_amd64.tar.gz"
      sha256 "d4303ad0c490bccfee273948345f6da68ce8257f9de8d874fb8ef9aeecd27bb5"
      def install
        bin.install "lazyliner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/li-brandon/lazyliner/releases/download/v0.0.1/lazyliner_0.0.1_linux_arm64.tar.gz"
      sha256 "9ac5df323d6e9dbffa9b9337ca86c2771f3923cb9cb2b31d54e6696030905f71"
      def install
        bin.install "lazyliner"
      end
    end
  end

  test do
    system "#{bin}/lazyliner", "--version"
  end
end
