# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TodoistAi < Formula
  desc "AI-powered terminal UI for Todoist task management"
  homepage "https://github.com/li-brandon/todoist-ai"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/li-brandon/todoist-ai/releases/download/v0.1.0/todoist-ai_0.1.0_darwin_amd64.tar.gz"
      sha256 "eff82707ad8571a957678908ec217286339e84deef53711cc44a778de002e199"

      def install
        bin.install "todoist-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/li-brandon/todoist-ai/releases/download/v0.1.0/todoist-ai_0.1.0_darwin_arm64.tar.gz"
      sha256 "0ad599449dbb8ef2bf8a8f3cabb7a33a8987393acb556fbfebfa02ed3717a34e"

      def install
        bin.install "todoist-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/li-brandon/todoist-ai/releases/download/v0.1.0/todoist-ai_0.1.0_linux_amd64.tar.gz"
      sha256 "5d9e826294b47830c096df39956536c0b7008f39d28cb0ad14589d424cb3f7c9"
      def install
        bin.install "todoist-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/li-brandon/todoist-ai/releases/download/v0.1.0/todoist-ai_0.1.0_linux_arm64.tar.gz"
      sha256 "fc83b3985dbd686d6bbaa69da581823ca33b1da8846d8a51bfeeb770403d3261"
      def install
        bin.install "todoist-ai"
      end
    end
  end

  test do
    system "#{bin}/todoist-ai", "--version"
  end
end
